import { useMemo } from 'react'
import { Link } from 'react-router-dom'
import { Card } from '../components/ui'
import { academicLevelLabels, academicResult, academicLevels, aspectLevel, aspects, aspectLabels, dictationPercentage, readingLevel, type AcademicKind, type AcademicRecord, type AcademicRules } from '../services/schoolDomain'
import type { Student } from '../models/domain'

export type AcademicTab = 'summary' | 'reading' | 'dictation' | 'comprehension'
export type AcademicFilters = { grade: string; group: string; from: string; through: string; mode: 'group' | 'student'; studentId: number }
type ChartRow = { label: string; values: (number | null)[]; href?: string }
const levelColors = ['#d84a4a', '#f1bf32', '#70bd62', '#27894b']
const aspectColors: Record<string, string> = { REQUIRES_SUPPORT: '#d84a4a', STANDARD: '#f1bf32', ADVANCED: '#27894b' }
const percent = (value: number) => `${value.toLocaleString('es-MX', { maximumFractionDigits: 1 })}%`
const rangeLabel = (from: string, through: string) => from || through ? `${from || 'Sin límite inicial'} — ${through || 'Sin límite final'}` : 'Todas las fechas'
function latestPerStudent(records: AcademicRecord[]) {
  const latest = new Map<number, AcademicRecord>()
  for (const record of [...records].sort((a, b) => a.school_date.localeCompare(b.school_date) || a.recorded_at - b.recorded_at || a.id - b.id)) latest.set(record.student_id, record)
  return [...latest.values()]
}

function DataChart({ title, unit, period, sample, series, rows, maxValue = 1, pointChart = false, rowHeading }: { title: string; unit: string; period: string; sample: string; series: { label: string; color: string }[]; rows: ChartRow[]; maxValue?: number; pointChart?: boolean; rowHeading?: string }) {
  const safeMax = Math.max(maxValue, ...rows.flatMap((row) => row.values.map((value) => value ?? 0)), 1)
  return <Card className="academic-chart-card">
    <div className="section-header"><div><h3>{title}</h3><p>Unidad: {unit} · Período: {period} · Muestra: {sample}</p></div></div>
    {rows.length === 0 ? <p className="academic-empty">Todavía no hay evaluaciones en este período.</p> : <>
      <div className="academic-legend" aria-label="Leyenda de niveles">{series.map((entry) => <span key={entry.label}><i style={{ backgroundColor: entry.color }} />{entry.label}</span>)}</div>
      {!pointChart && <div className="academic-scale" aria-label={`Escala de alumnos de cero a ${safeMax}`}>Escala de alumnos: 0–{safeMax} (personas)</div>}
      <div className={`academic-chart${pointChart ? ' academic-chart-points' : ''}`} role="group" aria-label={`${title}. ${unit}. ${period}. ${sample}. Gráfica de barras; consulta la tabla accesible siguiente.`}>
        {rows.map((row, index) => <div className="academic-chart-row" key={`${row.label}-${index}`}>
          {row.href ? <Link className="academic-chart-label" to={row.href}>{row.label}</Link> : <span className="academic-chart-label">{row.label}</span>}
          <div className="academic-chart-bars">{row.values.map((value, seriesIndex) => value === null ? null : <div className="academic-chart-bar-line" key={series[seriesIndex]?.label ?? seriesIndex}>
            <span className="academic-chart-series-label">{series[seriesIndex]?.label ?? ''}</span>
            <span className="academic-chart-track"><span className="academic-chart-bar" style={{ width: `${Math.max(value > 0 ? 1 : 0, value / safeMax * 100)}%`, backgroundColor: series[seriesIndex]?.color ?? '#1267d6' }} /></span>
            <strong>{pointChart ? percent(value) : value.toLocaleString('es-MX', { maximumFractionDigits: 2 })}</strong>
          </div>)}</div>
        </div>)}
      </div>
      <details className="academic-data-details"><summary>Ver datos de la gráfica</summary><div className="table-scroll"><table className="data-table academic-chart-table"><caption>{title} — mismos valores que la gráfica; {unit}; {period}; {sample}</caption><thead><tr><th scope="col">{rowHeading ?? (pointChart ? 'Alumno' : 'Nivel')}</th>{series.map((entry) => <th scope="col" key={entry.label}>{entry.label}</th>)}</tr></thead><tbody>{rows.map((row, index) => <tr key={`${row.label}-table-${index}`}><th scope="row">{row.href ? <Link to={row.href}>{row.label}</Link> : row.label}</th>{series.map((entry, seriesIndex) => <td key={entry.label}>{row.values[seriesIndex] === null || row.values[seriesIndex] === undefined ? '—' : pointChart ? percent(row.values[seriesIndex]!) : row.values[seriesIndex]!.toLocaleString('es-MX', { maximumFractionDigits: 2 })}</td>)}</tr>)}</tbody></table></div></details>
    </>}
  </Card>
}

function TrendChart({ title, unit, period, sample, records, students, valueFor, seriesLabel = unit, formatValue = percent }: { title: string; unit: string; period: string; sample: string; records: AcademicRecord[]; students: readonly Student[]; valueFor: (record: AcademicRecord) => number | null; seriesLabel?: string; formatValue?: (value: number) => string }) {
  const points = records.map((record) => ({ record, value: valueFor(record), student: students.find((entry) => entry.student_id === record.student_id) })).filter((entry): entry is { record: AcademicRecord; value: number; student: Student | undefined } => entry.value !== null).sort((a, b) => a.record.school_date.localeCompare(b.record.school_date) || a.record.recorded_at - b.record.recorded_at)
  const max = Math.max(1, ...points.map(({ value }) => value)); const width = 700; const height = 200; const pad = 32
  const coords = points.map((point, index) => ({ ...point, x: points.length < 2 ? width / 2 : pad + index * (width - pad * 2) / (points.length - 1), y: height - pad - point.value / max * (height - pad * 2) }))
  const path = coords.length >= 3 ? coords.map(({ x, y }, index) => `${index ? 'L' : 'M'}${x},${y}`).join(' ') : ''
  return <Card className="academic-chart-card"><div className="section-header"><div><h3>{title}</h3><p>Unidad: {unit} · Período: {period} · Muestra: {sample}</p></div></div>
    {coords.length === 0 ? <p className="school-help">Sin datos evaluados para los filtros actuales.</p> : <>
      <div className="academic-trend-layout"><span className="academic-y-unit">{unit}</span><div className="academic-trend-visual" role="img" aria-label={`${title}: ${coords.length} puntos de ${seriesLabel}. ${coords.length < 2 ? 'Se muestra un punto sin inventar tendencia.' : coords.length < 3 ? 'Se muestran puntos sin unir porque la muestra es pequeña.' : 'Se muestra evolución entre registros.'}`}>
        <svg viewBox={`0 0 ${width} ${height}`} preserveAspectRatio="none" aria-hidden="true"><line x1={pad} y1={height - pad} x2={width - pad} y2={height - pad} className="academic-axis" />{path && <path d={path} className="academic-trend-line" />}{coords.map(({ x, y, record }) => <circle key={record.id} cx={x} cy={y} r="5" className="academic-trend-point" />)}</svg>
        <div className="academic-trend-dates">{coords.map(({ record }) => <span key={record.id}>{record.school_date}</span>)}</div>
        <div className="academic-trend-labels">{coords.map(({ record, value, student }) => <span key={record.id}>{record.school_date} · {student?.preferred_name ?? student?.name ?? `ID ${record.student_id}`} · {formatValue(value)}</span>)}</div>
      </div></div>
      <details className="academic-data-details"><summary>Ver datos de la gráfica</summary><div className="table-scroll"><table className="data-table academic-chart-table"><caption>{title} — mismos puntos que la gráfica; {unit}; {period}; {sample}</caption><thead><tr><th scope="col">Fecha</th><th scope="col">Alumno</th><th scope="col">{seriesLabel}</th><th scope="col">Registro</th></tr></thead><tbody>{coords.map(({ record, value, student }) => <tr key={record.id}><td>{record.school_date}</td><td>{student?.name ?? `ID ${record.student_id}`}</td><td>{formatValue(value)}</td><td><Link to="#academic-history">Consultar registro {record.id}</Link></td></tr>)}</tbody></table></div></details>
    </>}
  </Card>
}

export function AcademicAnalytics({ tab, filters, students, records, rules, onSelectTab = () => {}, onRegister = () => {} }: { tab: AcademicTab; filters: AcademicFilters; students: readonly Student[]; records: AcademicRecord[]; rules: AcademicRules; onSelectTab?: (tab: AcademicTab) => void; onRegister?: (kind: AcademicKind | null) => void }) {
  const roster = useMemo(() => students.filter((student) => (!filters.grade || String(student.grade) === filters.grade) && (!filters.group || student.group === filters.group) && (filters.mode !== 'student' || student.student_id === filters.studentId)), [students, filters])
  const ids = new Set(roster.map(({ student_id }) => student_id))
  const scoped = records.filter((record) => ids.has(record.student_id) && (!filters.from || record.school_date >= filters.from) && (!filters.through || record.school_date <= filters.through))
  const period = rangeLabel(filters.from, filters.through)
  const summary = tab === 'summary'
  const kind: AcademicKind | null = tab === 'reading' ? 'READING' : tab === 'dictation' ? 'DICTATION' : tab === 'comprehension' ? 'COMPREHENSION' : null
  const only = kind ? scoped.filter((record) => record.kind === kind) : scoped
  const latestReading = latestPerStudent(scoped.filter((record) => record.kind === 'READING'))
  const latestDictation = latestPerStudent(scoped.filter((record) => record.kind === 'DICTATION'))
  const latestComprehension = latestPerStudent(scoped.filter((record) => record.kind === 'COMPREHENSION'))
  const isIndividual = filters.mode === 'student'
  const studentName = students.find(({ student_id }) => student_id === filters.studentId)?.preferred_name ?? 'Alumno'
  const per = (values: number[]) => Math.max(1, ...values)
  if (summary) {
    const evaluatedCount = (items: AcademicRecord[], kindName: AcademicKind) => items.filter((record) => record.kind === kindName && !(record.kind === 'COMPREHENSION' && aspects.every((aspect) => record.scores[aspect] === null))).length
    const readingCoverage = [1, 2, 3, 4, 5, 6].filter((grade) => roster.some((student) => student.grade === grade)).map((grade) => { const evaluated = latestReading.filter((record) => record.kind === 'READING' && record.grade === grade).length; return { grade, pending: Math.max(0, roster.filter((student) => student.grade === grade).length - evaluated) } })
    const readingDist = readingCoverage.filter(({ grade }) => latestReading.some((record) => record.kind === 'READING' && record.grade === grade)).map(({ grade }) => { const gradeRecords = latestReading.filter((record) => record.kind === 'READING' && record.grade === grade); return { label: `${grade}° grado`, values: academicLevels.map((level) => gradeRecords.filter((record) => record.kind === 'READING' && readingLevel(grade, record.ppm, rules) === level).length) } })
    const dictationConfigured = rules.dictation.boundaries !== null
    const dictationDist = dictationConfigured ? academicLevels.map((level) => ({ label: academicLevelLabels[level], values: [latestDictation.filter((record) => record.kind === 'DICTATION' && academicResult(record, rules).level === level).length] })) : []
    const dictationPercentages = latestDictation.filter((record) => record.kind === 'DICTATION').map((record) => ({ label: students.find(({ student_id }) => student_id === record.student_id)?.preferred_name ?? `ID ${record.student_id}`, values: [dictationPercentage(record.correct_words, record.total_words)], href: '#academic-history' }))
    const comprehensionDist = aspects.filter((aspect) => latestComprehension.some((record) => record.kind === 'COMPREHENSION' && record.scores[aspect] !== null)).map((aspect) => ({ label: aspectLabels[aspect], values: (['REQUIRES_SUPPORT', 'STANDARD', 'ADVANCED'] as const).map((level) => latestComprehension.filter((record) => record.kind === 'COMPREHENSION' && record.scores[aspect] !== null && aspectLevel(record.scores[aspect]!, record.denominators[aspect]) === level).length) }))
    const comprehensionCoverage = aspects.map((aspect) => ({ aspect, pending: Math.max(0, roster.length - latestComprehension.filter((record) => record.kind === 'COMPREHENSION' && record.scores[aspect] !== null).length) }))
    const counts = [
      { name: 'Fluidez lectora', records: latestReading.length, evaluated: latestReading.length, unevaluated: Math.max(0, roster.length - latestReading.length) },
      { name: 'Dictado', records: latestDictation.length, evaluated: latestDictation.length, unevaluated: Math.max(0, roster.length - latestDictation.length) },
      { name: 'Comprensión', records: latestComprehension.length, evaluated: evaluatedCount(latestComprehension, 'COMPREHENSION'), unevaluated: Math.max(0, roster.length - evaluatedCount(latestComprehension, 'COMPREHENSION')) },
    ]
    const allUnevaluated = counts.every((item) => item.evaluated === 0)
    const coverageCeiling = Math.max(1, roster.length)
    return <section className="academic-analytics" aria-label="Resumen académico del grupo">
      <div className="academic-indicator-counts">{counts.map((item) => <Card key={item.name} className="academic-coverage-card"><h3>{item.name}</h3><strong>{item.evaluated} evaluados</strong><span className="academic-pending">{item.unevaluated} pendientes</span><span className="academic-coverage-track" aria-label={`${item.unevaluated} alumnos sin evaluar`}><i style={{ width: `${item.unevaluated / coverageCeiling * 100}%` }} /></span></Card>)}</div>
      <div className="academic-result-links" aria-label="Resultados por indicador">{counts.map((item, index) => { const destination: AcademicTab = (['reading', 'dictation', 'comprehension'] as AcademicTab[])[index]; return <button key={item.name} type="button" className="academic-result-link" onClick={() => onSelectTab(destination)}><span>{item.name}</span><strong>{item.evaluated}/{roster.length} evaluados</strong><span>Ver resultados →</span></button> })}</div>
      {!allUnevaluated && <div className="academic-register-row"><button type="button" onClick={() => onRegister(null)}>Registrar evaluación</button><span>Elige el indicador en el formulario.</span></div>}
      <p className="academic-visible-period">Período: {period} · Evaluados: {counts.reduce((total, item) => total + item.evaluated, 0)} resultados alumno/indicador.</p><details className="academic-method-details"><summary>Cómo se calculan los resultados</summary><p>Para las distribuciones se usa la última evaluación de cada alumno dentro del período; las tendencias individuales incluyen todos los registros. “Sin evaluar” se cuenta como cobertura pendiente y se excluye de los niveles. Fluidez conserva umbrales por grado. La ponderación general de comprensión sigue sin configurar.</p></details>
      {allUnevaluated ? <Card className="academic-no-evaluations"><strong>Todavía no hay evaluaciones en este período</strong><span>{roster.length} alumnos pendientes por indicador.</span><button type="button" onClick={() => onRegister(null)}>Registrar evaluación</button></Card> : <div className="academic-chart-grid">
        {readingDist.some((row) => row.values.some((value) => value > 0)) && <DataChart title="Fluidez lectora · niveles por grado" unit="alumnos por nivel" period={period} sample={`${counts[0].evaluated} evaluados; ${counts[0].unevaluated} pendientes`} rowHeading="Grado" series={academicLevels.map((level, index) => ({ label: academicLevelLabels[level], color: levelColors[index] }))} rows={readingDist} maxValue={coverageCeiling} />}
        {dictationConfigured ? dictationDist.some((row) => row.values[0] > 0) && <DataChart title="Dictado · distribución por nivel" unit="alumnos" period={period} sample={`${counts[1].evaluated} evaluados; ${counts[1].unevaluated} pendientes`} series={academicLevels.map((level, index) => ({ label: academicLevelLabels[level], color: levelColors[index] }))} rows={dictationDist} maxValue={coverageCeiling} /> : dictationPercentages.length > 0 ? <DataChart title="Porcentaje de palabras correctas" unit="porcentaje de palabras correctas (0–100 %)" period={period} sample={`${counts[1].evaluated} evaluados; ${counts[1].unevaluated} pendientes`} rowHeading="Alumno" series={[{ label: 'Porcentaje correcto', color: '#1267d6' }]} rows={dictationPercentages} maxValue={100} pointChart /> : <Card className="academic-empty-compact">Sin evaluaciones de dictado en este período. Rangos de clasificación: {dictationConfigured ? 'configurados' : 'Sin configurar'}.</Card>}
        {comprehensionDist.length > 0 && <div><DataChart title="Comprensión · niveles por aspecto" unit="alumnos por nivel del aspecto" period={period} sample={`${counts[2].evaluated} evaluados; ${counts[2].unevaluated} pendientes`} rowHeading="Aspecto" series={[{ label: 'Requiere apoyo', color: aspectColors.REQUIRES_SUPPORT }, { label: 'En desarrollo', color: aspectColors.STANDARD }, { label: 'Logrado', color: aspectColors.ADVANCED }]} rows={comprehensionDist} maxValue={coverageCeiling} /><ul className="academic-pending-list">{comprehensionCoverage.filter(({ pending }) => pending > 0).map(({ aspect, pending }) => <li key={aspect}><span className="pending-dot" />{aspectLabels[aspect]}: Sin evaluar · {pending} alumnos</li>)}</ul></div>}
        {readingCoverage.some(({ pending }) => pending > 0) && <ul className="academic-pending-list academic-reading-pending">{readingCoverage.filter(({ pending }) => pending > 0).map(({ grade, pending }) => <li key={grade}><span className="pending-dot" />{grade}° grado · Sin evaluar: {pending} alumnos</li>)}</ul>}
      </div>}
      <div className="academic-insight-links"><Link to="#academic-history">Ir a registros para consultar, capturar o corregir</Link></div>
    </section>
  }
  if (tab === 'reading' && isIndividual) { const data = only.filter((r) => r.kind === 'READING'); return <section className="academic-analytics"><details className="academic-method-details"><summary>Cómo se calculan los resultados</summary><p>Período: {period} · Muestra: {data.length} registros. Se muestran todos los registros en PPM; la clasificación usa el grado guardado en cada evaluación.</p></details>{data.length ? <TrendChart title={`Fluidez lectora · ${studentName}`} unit="palabras por minuto (PPM)" period={period} sample={`${data.length} registros`} records={data} students={students} seriesLabel="PPM" formatValue={(value) => `${value.toLocaleString('es-MX')} PPM`} valueFor={(record) => record.kind === 'READING' ? record.ppm : null} /> : <NoIndicatorData kind="READING" roster={roster.length} hasRecords={records.some((record) => record.kind === 'READING')} onRegister={onRegister} />}</section> }
  if (tab === 'reading') {
    const readings = latestPerStudent(only.filter((record) => record.kind === 'READING'))
    const grades = [...new Set(readings.flatMap((record) => record.kind === 'READING' ? [record.grade] : []))].sort((a, b) => a - b)
    const coverage = [...new Set(roster.map((student) => student.grade))].sort((a, b) => a - b).map((grade) => ({ grade, pending: Math.max(0, roster.filter((student) => student.grade === grade).length - readings.filter((record) => record.kind === 'READING' && record.grade === grade).length) })).filter(({ pending }) => pending > 0)
    return <section className="academic-analytics"><details className="academic-method-details"><summary>Cómo se calculan los resultados</summary><p>Período: {period} · Muestra: {readings.length} alumnos evaluados de {roster.length}. Se usa la última evaluación por alumno; cada grado conserva sus umbrales propios. Pendientes se muestran aparte en gris.</p></details>{readings.length === 0 ? <NoIndicatorData kind="READING" roster={roster.length} hasRecords={records.some((record) => record.kind === 'READING')} onRegister={onRegister} /> : <><div className="academic-chart-grid">{grades.map((grade) => { const subset = readings.filter((record) => record.kind === 'READING' && record.grade === grade); const enrolled = roster.filter((s) => s.grade === grade).length; const rows = academicLevels.map((level) => ({ label: academicLevelLabels[level], values: [subset.filter((record) => record.kind === 'READING' && readingLevel(grade, record.ppm, rules) === level).length] })); return <DataChart key={grade} title={`Fluidez lectora · ${grade}° grado`} unit="alumnos por nivel" period={period} sample={`${subset.length} evaluados de ${enrolled} alumnos`} series={academicLevels.map((level, index) => ({ label: academicLevelLabels[level], color: levelColors[index] }))} rows={rows} maxValue={Math.max(1, ...[...new Set(roster.map((s) => s.grade))].map((g) => roster.filter((s) => s.grade === g).length))} /> })}</div>{coverage.length > 0 && <ul className="academic-pending-list">{coverage.map(({ grade, pending }) => <li key={grade}><span className="pending-dot" />{grade}° grado · Sin evaluar: {pending} alumnos</li>)}</ul>}</>}<HistoryAccessLink /></section>
  }
  if (tab === 'dictation' && isIndividual) { const data = only.filter((r) => r.kind === 'DICTATION'); return <section className="academic-analytics"><details className="academic-method-details"><summary>Cómo se calculan los resultados</summary><p>Período: {period} · Muestra: {data.length} registros. Se conservan todos los registros y se calcula el porcentaje de palabras correctas. {rules.dictation.boundaries ? 'La clasificación usa los rangos configurados.' : 'Las reglas de clasificación siguen sin configurar.'}</p></details>{data.length ? <TrendChart title={`Dictado · ${studentName}`} unit="porcentaje de palabras correctas" period={period} sample={`${data.length} registros`} records={data} students={students} seriesLabel="Palabras correctas" valueFor={(record) => record.kind === 'DICTATION' ? dictationPercentage(record.correct_words, record.total_words) : null} /> : <NoIndicatorData kind="DICTATION" roster={roster.length} hasRecords={records.some((record) => record.kind === 'DICTATION')} onRegister={onRegister} />}</section> }
  if (tab === 'dictation') {
    const dictations = latestPerStudent(only.filter((record) => record.kind === 'DICTATION'))
    const rows = dictations.filter((record) => record.kind === 'DICTATION').map((record) => ({ label: students.find(({ student_id }) => student_id === record.student_id)?.preferred_name ?? `ID ${record.student_id}`, values: [dictationPercentage(record.correct_words, record.total_words)], href: '#academic-history' }))
    const levelRows = academicLevels.map((level) => ({ label: academicLevelLabels[level], values: [dictations.filter((record) => academicResult(record, rules).level === level).length] }))
    return <section className="academic-analytics"><details className="academic-method-details"><summary>Cómo se calculan los resultados</summary><p>Período: {period} · Muestra: {rows.length} evaluados de {roster.length}. Se muestra la última evaluación por alumno con escala fija de 0–100 %. {rules.dictation.boundaries ? 'La distribución por niveles usa los rangos configurados.' : 'Las reglas de clasificación siguen sin configurar; solo se muestran porcentajes.'}</p></details>{rows.length ? <><div className="academic-chart-grid"><DataChart title="Porcentaje de palabras correctas" unit="porcentaje de palabras correctas (0–100 %)" period={period} sample={`${rows.length} evaluados`} series={[{ label: 'Porcentaje correcto', color: '#1267d6' }]} rows={rows} maxValue={100} pointChart />{rules.dictation.boundaries && <DataChart title="Dictado · distribución por nivel" unit="alumnos por nivel" period={period} sample={`${rows.length} evaluados`} series={academicLevels.map((level, index) => ({ label: academicLevelLabels[level], color: levelColors[index] }))} rows={levelRows} maxValue={Math.max(1, roster.length)} />}</div>{rows.length < roster.length && <ul className="academic-pending-list"><li><span className="pending-dot" />Sin evaluar en Dictado: {roster.length - rows.length} alumnos</li></ul>}</> : <NoIndicatorData kind="DICTATION" roster={roster.length} hasRecords={records.some((record) => record.kind === 'DICTATION')} onRegister={onRegister} />}<HistoryAccessLink /></section>
  }
  if (tab === 'comprehension' && isIndividual) {
    const comprehension = only.filter((record) => record.kind === 'COMPREHENSION')
    const aspectLatest = Object.fromEntries(aspects.map((aspect) => [aspect, [...comprehension].filter((record) => record.kind === 'COMPREHENSION' && record.scores[aspect] !== null).sort((a, b) => b.school_date.localeCompare(a.school_date) || b.recorded_at - a.recorded_at || b.id - a.id)[0] as Extract<AcademicRecord, { kind: 'COMPREHENSION' }> | undefined]))
    const aspectRows = aspects.map((aspect) => { const record = aspectLatest[aspect]; return { label: aspectLabels[aspect], values: [record?.scores[aspect] ?? null, record?.denominators[aspect] ?? null] } }).filter((row) => row.values[0] !== null)
    if (!comprehension.length) return <section className="academic-analytics"><details className="academic-method-details"><summary>Cómo se calculan los resultados</summary><p>Período: {period} · Muestra: 0 registros.</p></details><NoIndicatorData kind="COMPREHENSION" roster={roster.length} hasRecords={records.some((record) => record.kind === 'COMPREHENSION')} onRegister={onRegister} /></section>
    return <section className="academic-analytics"><details className="academic-method-details"><summary>Cómo se calculan los resultados</summary><p>Período: {period} · Muestra: {comprehension.length} registros. La gráfica presenta el dato evaluado más reciente de cada aspecto; las tendencias conservan todos los registros del período. Los aspectos vacíos se omiten, no se convierten en cero.</p></details><div className="academic-chart-grid"><div><DataChart title={`Comprensión · aciertos por aspecto · ${studentName}`} unit="aciertos por aspecto" period={period} sample={`${aspectRows.length} aspectos con dato`} rowHeading="Aspecto" series={[{ label: 'Aciertos', color: '#1267d6' }, { label: 'Preguntas', color: '#9aa7b4' }]} rows={aspectRows} maxValue={Math.max(1, ...aspectRows.flatMap(({ values }) => values.map((v) => v ?? 0)))} /><ul className="academic-pending-list">{aspects.filter((aspect) => !aspectLatest[aspect]).map((aspect) => <li key={aspect}>{aspectLabels[aspect]}: Sin evaluar</li>)}</ul></div><div className="academic-trends-by-aspect">{aspects.map((aspect) => { const aspectRecords = comprehension.filter((record) => record.kind === 'COMPREHENSION' && record.scores[aspect] !== null); return aspectRecords.length ? <TrendChart key={aspect} title={`Comprensión ${aspectLabels[aspect].toLowerCase()}`} unit="porcentaje de aciertos" period={period} sample={`${aspectRecords.length} registros`} records={aspectRecords} students={students} seriesLabel={aspectLabels[aspect]} valueFor={(record) => record.kind === 'COMPREHENSION' && record.scores[aspect] !== null ? record.scores[aspect]! / record.denominators[aspect] * 100 : null} /> : <Card key={aspect} className="academic-empty-compact">{aspectLabels[aspect]}: Sin evaluar en este período.</Card> })}</div></div></section>
  }
  const comprehension = latestPerStudent(only.filter((record) => record.kind === 'COMPREHENSION'))
    const compRows = aspects.map((aspect) => ({ label: aspectLabels[aspect], values: (['REQUIRES_SUPPORT', 'STANDARD', 'ADVANCED'] as const).map((level) => comprehension.filter((record) => record.kind === 'COMPREHENSION' && record.scores[aspect] !== null && aspectLevel(record.scores[aspect]!, record.denominators[aspect]) === level).length) })).filter((row) => row.values.some((value) => value > 0))
  const compCoverage = aspects.map((aspect) => ({ aspect, pending: Math.max(0, roster.length - comprehension.filter((record) => record.kind === 'COMPREHENSION' && record.scores[aspect] !== null).length) })).filter(({ pending }) => pending > 0)
  if (!compRows.length) return <section className="academic-analytics"><details className="academic-method-details"><summary>Cómo se calculan los resultados</summary><p>Período: {period} · Muestra: {comprehension.length} evaluaciones; la clasificación se hace por aspecto. La ponderación general sigue sin configurar.</p></details><NoIndicatorData kind="COMPREHENSION" roster={roster.length} hasRecords={records.some((record) => record.kind === 'COMPREHENSION')} onRegister={onRegister} /></section>
  return <section className="academic-analytics"><details className="academic-method-details"><summary>Cómo se calculan los resultados</summary><p>Período: {period} · Muestra: {comprehension.length} registros. Se usa la última evaluación por alumno; los aspectos sin dato se excluyen y se cuentan como pendientes. La ponderación general sigue sin configurar.</p></details><div><DataChart title="Comprensión · niveles por aspecto" unit="alumnos por nivel" period={period} sample={`${comprehension.length} con registro`} rowHeading="Aspecto" series={[{ label: 'Requiere apoyo', color: aspectColors.REQUIRES_SUPPORT }, { label: 'En desarrollo', color: aspectColors.STANDARD }, { label: 'Logrado', color: aspectColors.ADVANCED }]} rows={compRows} maxValue={per(compRows.flatMap(({ values }) => values))} />{compCoverage.length > 0 && <ul className="academic-pending-list">{compCoverage.map(({ aspect, pending }) => <li key={aspect}><span className="pending-dot" />{aspectLabels[aspect]} · Sin evaluar: {pending} alumnos</li>)}</ul>}</div><HistoryAccessLink /></section>
}

function HistoryAccessLink() { return <div className="academic-insight-links"><Link to="#academic-history">Abrir registros para consultar, capturar o corregir</Link></div> }

function NoIndicatorData({ kind, roster, hasRecords, onRegister }: { kind: AcademicKind; roster: number; hasRecords: boolean; onRegister: (kind: AcademicKind | null) => void }) {
  const label = kind === 'READING' ? 'Fluidez lectora' : kind === 'DICTATION' ? 'Dictado' : 'Comprensión'
  return <Card className="academic-no-evaluations"><strong>{hasRecords ? 'Ninguna evaluación coincide con los filtros' : 'Todavía no hay evaluaciones en este período'}</strong><span>{roster} alumnos pendientes en {label}.</span><button type="button" onClick={() => onRegister(kind)}>Registrar evaluación</button></Card>
}
