import { useEffect, useState } from 'react'
import { Button, Card, PageHeader } from '../components/ui'
import { DemoBackupPanel } from '../components/DemoBackupPanel'
import { DemoPanelDataService } from '../services/DemoPanelDataService'
import { demoPanelService } from '../services/demoPanelService'
import { academicLevels, academicLevelLabels, aspects, aspectLabels, cloneAcademicRules, cloneAttendanceRules, type AcademicRules, type AcademicLevel, type AttendanceRules } from '../services/schoolDomain'

type State = { status: 'loading' } | { status: 'error' } | { status: 'ready'; academic: AcademicRules; attendance: AttendanceRules }
const rewardLevels: AcademicLevel[] = [...academicLevels]
function numberValue(value: string) { return value === '' ? null : Number(value) }

export function SchoolConfigurationPage({ service = demoPanelService as DemoPanelDataService }: { service?: DemoPanelDataService }) {
  const [state, setState] = useState<State>({ status: 'loading' }); const [attempt, setAttempt] = useState(0); const [academic, setAcademic] = useState<AcademicRules | null>(null); const [attendance, setAttendance] = useState<AttendanceRules | null>(null); const [review, setReview] = useState(false); const [error, setError] = useState(''); const [notice, setNotice] = useState(''); const [busy, setBusy] = useState(false)
  useEffect(() => { let live = true; setState({ status: 'loading' }); service.getSchoolRules().then((rules) => { if (live) { setState({ status: 'ready', academic: rules.academic, attendance: rules.attendance }); setAcademic(cloneAcademicRules(rules.academic)); setAttendance(cloneAttendanceRules(rules.attendance)) } }).catch(() => { if (live) setState({ status: 'error' }) }); return () => { live = false } }, [service, attempt])
  const setBoundary = (kind: 'dictation' | 'overall', index: 0 | 1 | 2, value: string) => setAcademic((current) => { if (!current) return current; const next = cloneAcademicRules(current); const old = kind === 'dictation' ? next.dictation.boundaries : next.comprehension.overall.boundaries; const values: [number, number, number] = old ? [...old] : [0, 0, 0]; values[index] = value === '' ? 0 : Number(value); const result = value === '' && values.every((item) => item === 0) ? null : values; if (kind === 'dictation') next.dictation.boundaries = result; else next.comprehension.overall.boundaries = result; return next })
  const setSave = async () => { if (!academic || !attendance || state.status !== 'ready') return; setBusy(true); setError(''); setNotice(''); try { const saved = await service.updateSchoolRules(academic, attendance, state.academic.version, state.attendance.version); setState({ status: 'ready', ...saved }); setAcademic(cloneAcademicRules(saved.academic)); setAttendance(cloneAttendanceRules(saved.attendance)); setReview(false); setNotice(`Reglas guardadas como versión académica ${saved.academic.version} y asistencia ${saved.attendance.version}. Afectan aplicaciones futuras.`) } catch (reason) { setError(reason instanceof Error ? reason.message : 'No se guardó la configuración; se conservó el borrador.') } finally { setBusy(false) } }
  if (state.status === 'loading') return <><PageHeader eyebrow="SISTEMA · DEMOSTRACIÓN" title="Configuración escolar" description="Reglas académicas y de asistencia para futuras aplicaciones." /><Card role="status">Cargando configuración…</Card></>
  if (state.status === 'error' || !academic || !attendance) return <><PageHeader eyebrow="SISTEMA · DEMOSTRACIÓN" title="Configuración escolar" description="Reglas académicas y de asistencia para futuras aplicaciones." /><Card role="alert">No se pudo consultar la configuración. <Button onClick={() => setAttempt((value) => value + 1)}>Reintentar</Button></Card></>
  return <>
    <PageHeader eyebrow="SISTEMA · SOLO DEMOSTRACIÓN" title="Configuración escolar" description="Versiona rangos, criterios e importes que se usarán en aplicaciones futuras." />
    <Card className="school-demo-note"><strong>Configuración local de demostración</strong><span>Las reglas se guardan en este navegador y no cambian aplicaciones ni movimientos ya registrados. Áureos académicos aparecen como “Sin configurar” hasta que indiques sus importes. Los pesos y rangos generales de comprensión también empiezan sin configurar. No hay sincronización con la terminal.</span></Card>
    <DemoBackupPanel />
    <Card className="school-config-section"><h2>Lectura · PPM por grado</h2><p className="school-help">Rangos iniciales proporcionados por el usuario; no se verifican como estándares oficiales. Límites inferiores incluidos; cada frontera pasa al siguiente nivel.</p><div className="school-config-table"><div className="school-config-head"><span>Grado</span><span>Apoyo &lt;</span><span>Se acerca desde</span><span>Estándar desde</span><span>Avanzado desde</span></div>{[1, 2, 3, 4, 5, 6].map((grade) => <div className="school-config-row" key={grade}><strong>{grade}°</strong>{academic.reading[grade].map((value, index) => <label key={index}><span>{['Se acerca', 'Estándar', 'Avanzado'][index]} desde</span><input type="number" min="0" max="65535" step="1" value={value} onChange={(event) => setAcademic((current) => { if (!current) return current; const next = cloneAcademicRules(current); next.reading[grade][index] = Number(event.target.value); return next })} /></label>)}<span>&lt; valor 1 = Requiere apoyo</span></div>)}</div><p className="school-help">Iniciales (límite: apoyo / se acerca / estándar / avanzado): 1° 15/35/60; 2° 35/60/85; 3° 60/85/100; 4° 85/100/115; 5° 100/115/125; 6° 115/125/135.</p>
      <h3>Importe por nivel · Lectura</h3><RewardInputs values={academic.readingAureos} onChange={(level, value) => setAcademic((current) => { if (!current) return current; const next = cloneAcademicRules(current); next.readingAureos[level] = numberValue(value); return next })} />
    </Card>
    <Card className="school-config-section"><h2>Dictado · rangos porcentuales</h2><p className="school-help">Bandas continuas de 0 a 100 %. Cada frontera está incluida en el nivel siguiente; debe haber tres fronteras crecientes menores a 100.</p><BoundaryInputs boundaries={academic.dictation.boundaries} onChange={(index, value) => setBoundary('dictation', index, value)} /><h3>Importe por nivel · Dictado</h3><RewardInputs values={academic.dictation.aureos} onChange={(level, value) => setAcademic((current) => { if (!current) return current; const next = cloneAcademicRules(current); next.dictation.aureos[level] = numberValue(value); return next })} /></Card>
    <Card className="school-config-section"><h2>Comprensión · aspectos y ponderación</h2><p className="school-help">El total bruto usa solo aspectos evaluados. Un aspecto vacío se excluye; nunca se convierte a cero. Los porcentajes ponderados se normalizan con los pesos de los aspectos evaluados.</p><div className="school-config-row school-config-three">{aspects.map((aspect) => <label key={aspect}>{aspectLabels[aspect]} · número de preguntas<input type="number" min="1" max="100" step="1" value={academic.comprehension.denominators[aspect]} onChange={(event) => setAcademic((current) => { if (!current) return current; const next = cloneAcademicRules(current); next.comprehension.denominators[aspect] = Number(event.target.value); return next })} /></label>)}</div>
      <div className="school-config-row school-config-three">{aspects.map((aspect) => <label key={aspect}>Peso {aspectLabels[aspect]} (%)<input type="number" min="0" max="100" step="0.01" placeholder="Sin configurar" value={academic.comprehension.weights?.[aspect] ?? ''} onChange={(event) => setAcademic((current) => { if (!current) return current; const next = cloneAcademicRules(current); if (event.target.value === '') next.comprehension.weights = null; else { const currentWeights = next.comprehension.weights ?? { LITERAL: 0, INFERENTIAL: 0, CRITICAL: 0 }; currentWeights[aspect] = Number(event.target.value); next.comprehension.weights = currentWeights } return next })} /></label>)}</div><p className="school-help">Los pesos deben configurarse y sumar 100 %. Ahora: {academic.comprehension.weights ? `${aspects.reduce((sum, aspect) => sum + academic.comprehension.weights![aspect], 0)}%` : 'Sin configurar'}.</p>
      <label className="school-config-mode">Aplicar Áureos por<select value={academic.comprehension.rewardMode} onChange={(event) => setAcademic((current) => current ? { ...cloneAcademicRules(current), comprehension: { ...cloneAcademicRules(current).comprehension, rewardMode: event.target.value as 'ASPECTS' | 'OVERALL' } } : current)}><option value="ASPECTS">Nivel de cada aspecto (literal, inferencial, crítica)</option><option value="OVERALL">Nivel general ponderado</option></select></label>
      {academic.comprehension.rewardMode === 'ASPECTS' ? <>{aspects.map((aspect) => <section className="school-aspect-config" key={aspect}><h3>{aspectLabels[aspect]} · importe por resultado</h3><p>3 aciertos: Logrado · 2: En desarrollo · 0–1: Requiere apoyo (con los denominadores iniciales de 3 preguntas).</p><AspectRewardInputs values={academic.comprehension.aspectAureos[aspect]} onChange={(level, value) => setAcademic((current) => { if (!current) return current; const next = cloneAcademicRules(current); next.comprehension.aspectAureos[aspect][level] = numberValue(value); return next })} /></section>)}</> : <><h3>Rangos del resultado general ponderado (%) · comienzan Sin configurar</h3><BoundaryInputs boundaries={academic.comprehension.overall.boundaries} onChange={(index, value) => setBoundary('overall', index, value)} /><h3>Importe por nivel · Resultado general</h3><RewardInputs values={academic.comprehension.overall.aureos} onChange={(level, value) => setAcademic((current) => { if (!current) return current; const next = cloneAcademicRules(current); next.comprehension.overall.aureos[level] = numberValue(value); return next })} /></>}
    </Card>
    <Card className="school-config-section"><h2>Asistencia · horarios e importes para aplicaciones futuras</h2><div className="school-config-row school-config-three"><label>Hora límite puntual<input type="time" value={attendance.punctual_until} onChange={(event) => setAttendance((current) => current ? { ...current, punctual_until: event.target.value } : current)} /></label><label>Retardo hasta (incluido)<input type="time" value={attendance.grace_until} onChange={(event) => setAttendance((current) => current ? { ...current, grace_until: event.target.value } : current)} /></label><span className="school-help">Hora del panel convertida con America/Mexico_City.</span></div><div className="school-config-row school-config-four"><label>Primera llegada puntual<input type="number" step="1" value={attendance.first_amount} onChange={(event) => setAttendance((current) => current ? { ...current, first_amount: Number(event.target.value) } : current)} /></label><label>Retardo dentro del margen<input type="number" step="1" value={attendance.late_grace_amount} onChange={(event) => setAttendance((current) => current ? { ...current, late_grace_amount: Number(event.target.value) } : current)} /></label><label>Retardo posterior<input type="number" step="1" value={attendance.late_after_amount} onChange={(event) => setAttendance((current) => current ? { ...current, late_after_amount: Number(event.target.value) } : current)} /></label><label>Falta injustificada<input type="number" step="1" value={attendance.absent_unjustified_amount} onChange={(event) => setAttendance((current) => current ? { ...current, absent_unjustified_amount: Number(event.target.value) } : current)} /></label></div><p className="school-help">Los valores iniciales son +5, −5, −10 y −20. El desempate del primer lugar se determina por el mismo segundo registrado. La falta justificada y “Sin registrar” no generan importe.</p></Card>
    <Card className="school-config-actions"><p>Versión académica actual: {state.academic.version} · asistencia: {state.attendance.version}. Los cambios posteriores no alteran aplicaciones previas.</p>{error && <p className="school-error" role="alert">{error}</p>}{notice && <p className="school-success" role="status">{notice}</p>}{review && <div className="school-application-review" role="region" aria-label="Revisión de configuración"><h3>Confirmar configuración</h3><p>La siguiente versión será académica v{state.academic.version + 1} y asistencia v{state.attendance.version + 1}. Los registros y movimientos existentes se conservarán. Las reglas incompletas seguirán bloqueando sus aplicaciones monetarias.</p><div className="school-actions"><Button variant="primary" disabled={busy} onClick={setSave}>{busy ? 'Guardando…' : 'Confirmar cambios'}</Button><Button disabled={busy} onClick={() => setReview(false)}>Cancelar</Button></div></div>}{!review && <Button variant="primary" onClick={() => { setError(''); setReview(true) }}>Revisar cambios</Button>}</Card>
  </>
}

function BoundaryInputs({ boundaries, onChange }: { boundaries: [number, number, number] | null; onChange: (index: 0 | 1 | 2, value: string) => void }) { return <div className="school-config-row school-config-three">{(['Se acerca desde', 'Estándar desde', 'Avanzado desde'] as const).map((label, index) => <label key={label}>{label} (%)<input type="number" min="0.01" max="99.99" step="0.01" placeholder="Sin configurar" value={boundaries?.[index] ?? ''} onChange={(event) => onChange(index as 0 | 1 | 2, event.target.value)} /></label>)}</div> }
function RewardInputs({ values, onChange, labels = Object.fromEntries(academicLevels.map((level) => [level, academicLevelLabels[level]])) as Record<AcademicLevel, string> }: { values: Record<AcademicLevel, number | null>; onChange: (level: AcademicLevel, value: string) => void; labels?: Record<AcademicLevel, string> }) { return <div className="school-config-row school-config-four">{rewardLevels.map((level) => <label key={level}>{labels[level]} · Áureos<input type="number" step="1" placeholder="Sin configurar" value={values[level] ?? ''} onChange={(event) => onChange(level, event.target.value)} /></label>)}</div> }
function AspectRewardInputs({ values, onChange }: { values: Record<AcademicLevel, number | null>; onChange: (level: AcademicLevel, value: string) => void }) { return <div className="school-config-row school-config-three">{([{ level: 'REQUIRES_SUPPORT', label: 'Requiere apoyo' }, { level: 'STANDARD', label: 'En desarrollo' }, { level: 'ADVANCED', label: 'Logrado' }] as const).map(({ level, label }) => <label key={level}>{label} · Áureos<input type="number" step="1" placeholder="Sin configurar" value={values[level] ?? ''} onChange={(event) => onChange(level, event.target.value)} /></label>)}</div> }
